### ISSUE TITLE
Details on usage

### ISSUE THREAD

**Issue by dannyspanish** [gkoehler/LogiCircleDownloader#1]
Hi,

I've have being looking for a script to download my circle 2 footage and your script sounds brill. Would you be able to provide more details on the setup?

Ideally I would like to use it on my headless raspberry pi 3 to download the footage to my NAS do you know if this would work on a ARM based device?

Regards,
Danny.

**Comment by gkoehler** [comment]
I think it would, so you should try it! The script isn't perfect and I have
some unpublished updates I'm trying out, but feel free to improve via pull
request.

As far as the setup goes, I'm going to write a readme. Basically, an 'npm
install' should do everything, and you'll have to rename 'start.example.sh'
to 'start.sh', and edit it with your own logitech email and password.

Good luck!

**Comment by dannyspanish** [comment]
Thanks for getting back. Not had any luck getting it going but this is probably down to how my Pi is configured.
