### ISSUE TITLE
Logi changed their JSON response?

### ISSUE THREAD

**Issue by dmabram** [gkoehler/LogiCircleDownloader#4]
Just started happening in the last day or two: 

anniella:LogiCircleDownloader-master dabrams$ ./start.sh
(node:26697) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at https://video.logi.com/api/accessories reason: Unexpected token N in JSON at position 0
    at /Users/dabrams/Downloads/logicircle/LogiCircleDownloader-master/node_modules/node-fetch/lib/body.js:48:31
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:26697) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:26697) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by dannyspanish** [comment]
I'm also seeing the same error. My last download was on 13/02. I think Logitech have recently stopped access to their private API.

**Comment by kim82** [comment]
In ALL the headers add
'Origin': 'https://circle.logi.com'

ex:
let authResponse = await fetch('https://video.logi.com/api/accounts/authorization', {
        method: 'POST',
        headers: {
            'Accept': 'application/json, text/plain, */*',
            'Content-Type': 'application/json',
            'Origin': 'https://circle.logi.com'
        },
        body: JSON.stringify(user)
    });

**Comment by gkoehler** [comment]
Thanks, @kim82! If you (or anyone else) wants to make a PR for this change, I'll gladly accept it.

**Comment by gkoehler** [comment]
Got your PR merged, @kim82! Thanks for the help!

**Comment by gkoehler** [comment]
Fixed in #5
