### ISSUE TITLE
Limit of 80 video clips per camera

### ISSUE THREAD

**Issue by microsofa** [gkoehler/LogiCircleDownloader#7]
Hello, Great job on this, it works slick and saves a TON of time. Just one problem, it only downloads the most recent 80 videos. I tried changing the limit in the download file but anything over 100 then it returns an error: 

> $ ./start.sh
> (node:11272) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at https://video.logi.com/api/accessories/e742f7db-5eca-47d8-55d3-........./activities reason: Unexpected token L in JSON at position 0
>     at D:\lc\LogiCircleDownloader-master\node_modules\node-fetch\lib\body.js:48:31
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> (node:11272) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
> (node:11272) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

 I can switch the scanDirectionNewer to false and get the oldest videos instead, but it misses any in the middle. 

Can the limit be set to 8000 or more to grab all the videos?

**Comment by fomich0ff** [comment]
Probably it is too late but any way. 100 records is not an issue. It is API limitation. To download more than 100 videos you should do it in chunks by using `startActivityId` field in the body request. Please check it here [Get activities by accessory id](https://developers.logitech.com/circle/reference/get-activities-by-accessory-id).
You can replace `get_activities` with something like this:

```js
const get_activities = async (accessory, sessionCookie) => {
    let nextStartActivityId = null;
    let activities = [];

    do {
        let activitiesResponse = await fetch(`https://video.logi.com/api/accessories/${accessory.accessoryId}/activities`, {
            method: 'POST',
            headers: {
                'Accept': 'application/json, text/plain, */*',
                'Content-Type': 'application/json',
                'Cookie': sessionCookie,
                'Origin': 'https://circle.logi.com'
            },
            body: JSON.stringify({
                "extraFields": [
                    "activitySet"
                ],
                'startActivityId': nextStartActivityId,
                "operator": "<=",
                "limit": 100,
                "scanDirectionNewer": true,
                "filter": "relevanceLevel = 0 OR relevanceLevel >= 1"
            })
        }).then(response => response.json());

        activities = activities.concat(activitiesResponse.activities);
        nextStartActivityId = activitiesResponse.nextStartTime;

    } while (nextStartActivityId)

    return activities;
};
```

But be prepared: first run will take awhile to download all the videos you have

**Comment by hischampion** [comment]
This has been implemented.
