### ISSUE TITLE
Daily Summary?

### ISSUE THREAD

**Issue by skonesam** [gkoehler/LogiCircleDownloader#8]
Thanks for posting this -- works great! Do you know of a way of downloading (or creating and then downloading?) just the daily summary video? Or have any suggestions for how I might look for it?

**Comment by gkoehler** [comment]
Thanks! Glad to hear it's working well for you. 

I think that would be a really handy feature, but I haven't had the time to implement it myself. I'd certainly welcome a pull request if someone else figures it out. If I were working on it, I would load up the network inspector in Chrome, and then click the buttons that generate and download that daily summary. This should give you the request format that would be needed for the scripts.

**Comment by skonesam** [comment]
I've been experimenting, but the Daily Summary doesn't get put into the list of downloadable files. (Unless it's in some other directory/via some other API call or something? That'd be weird, but I didn't look for it.) Oh well. Will goof around with doing it the ugly way: browser UI scripting.
